version: '3.7'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  clickhouse-server:
    image: yandex/clickhouse-server:latest
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/clickhouse:/var/lib/clickhouse
      - ${CLICKHOUSE_CUSTOM_CONFIG}:/etc/clickhouse-server/config.xml
      - ${CLICKHOUSE_USERS_CUSTOM_CONFIG}:/etc/clickhouse-server/users.xml
      - ${CLICKHOUSE_HOST_LOG_PATH}:/var/log/clickhouse
    ports:
      - '${CLICKHOUSE_HTTP_PORT}:8123'
      - '${CLICKHOUSE_CLIENT_PORT}:9000'
      - '${CLICKHOUSE_NATIVE_PORT}:9009'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  clickhouse-client:
    image: yandex/clickhouse-client
    command: ['--host', 'server']
